import { Counter, Histogram, Gauge } from 'prom-client';
export declare const etlJobDuration: Histogram<"status" | "job_type">;
export declare const etlJobsTotal: Counter<"status" | "job_type">;
export declare const etlRecordsProcessed: Counter<"operation" | "job_type">;
export declare const cisSynced: Counter<"operation" | "ci_type">;
export declare const etlSyncLag: Gauge<"job_type">;
export declare const dataQualityScore: Gauge<"ci_type" | "dimension">;
export declare const changeDetectionRate: Counter<"ci_type" | "change_type">;
export declare const etlErrors: Counter<"error_type" | "job_type">;
export declare const activeEtlJobs: Gauge<"job_type">;
export declare const etlBatchSize: Histogram<"job_type">;
export declare const recordEtlJob: (_jobType: string, _status: "success" | "failure", _duration: number, _recordsProcessed: number) => void;
export declare const recordCiSync: (_ciType: string, _operation: "insert" | "update" | "delete") => void;
export declare const updateEtlSyncLag: (jobType: string, lagSeconds: number) => void;
export declare const updateDataQualityScore: (_dimension: string, _ciType: string, _score: number) => void;
export declare const recordChangeDetection: (_changeType: "create" | "update" | "delete", _ciType: string) => void;
export declare const recordEtlError: (jobType: string, errorType: string) => void;
export declare const updateActiveEtlJobs: (jobType: string, count: number) => void;
export declare const recordEtlBatchSize: (jobType: string, size: number) => void;
//# sourceMappingURL=etl-metrics.d.ts.map