import { Counter, Histogram, Gauge } from 'prom-client';
export declare const queueJobDuration: Histogram<"status" | "queue" | "job_name">;
export declare const queueJobsTotal: Counter<"status" | "queue" | "job_name">;
export declare const queueJobsWaiting: Gauge<"queue">;
export declare const queueJobsActive: Gauge<"queue">;
export declare const queueJobsCompleted: Gauge<"queue">;
export declare const queueJobsFailed: Gauge<"queue">;
export declare const queueJobWaitTime: Histogram<"queue" | "job_name">;
export declare const queueWorkersActive: Gauge<"queue">;
export declare const queueThroughput: Gauge<"queue">;
export declare const queueErrors: Counter<"queue" | "error_type">;
export declare const queueJobRetries: Counter<"queue" | "job_name">;
export declare const queueJobStalled: Counter<"queue">;
export declare const recordQueueJob: (_queue: string, _jobName: string, _status: "completed" | "failed", _duration: number, waitTime?: number) => void;
export declare const updateQueueStatus: (_queue: string, _waiting: number, _active: number, _completed: number, _failed: number) => void;
export declare const updateQueueWorkers: (queue: string, count: number) => void;
export declare const updateQueueThroughput: (queue: string, jobsPerSecond: number) => void;
export declare const recordQueueError: (queue: string, errorType: string) => void;
export declare const recordJobRetry: (queue: string, jobName: string) => void;
export declare const recordStalledJob: (queue: string) => void;
//# sourceMappingURL=queue-metrics.d.ts.map